import { ZoomVideoSdkUser } from './ZoomVideoSdkUser';
import { ZoomVideoSdkSessionAudioStatisticsInfoType, ZoomVideoSdkSessionVideoStatisticsInfoType, ZoomVideoSdkSessionShareStatisticsInfoType } from './ZoomVideoSdkSessionStatisticsInfo';
export declare type ZoomVideoSdkSessionType = {
    getSessionName: () => Promise<string>;
    getSessionID: () => Promise<string>;
    getSessionPassword: () => Promise<string>;
    getSessionHostName: () => Promise<string>;
    getSessionHost: () => Promise<ZoomVideoSdkUser>;
    getRemoteUsers: () => Promise<ZoomVideoSdkUser[]>;
    getMySelf: () => Promise<ZoomVideoSdkUser>;
    getSessionNumber: () => Promise<string>;
    getSessionPhonePasscode: () => Promise<string>;
    getAudioStatisticsInfo: () => Promise<ZoomVideoSdkSessionAudioStatisticsInfoType>;
    getAudioRecvFrequency: () => Promise<number>;
    getAudioRecvJitter: () => Promise<number>;
    getAudioRecvLatency: () => Promise<number>;
    getAudioRecvPacketLossAvg: () => Promise<number>;
    getAudioRecvPacketLossMax: () => Promise<number>;
    getAudioSendFrequency: () => Promise<number>;
    getAudioSendJitter: () => Promise<number>;
    getAudioSendLatency: () => Promise<number>;
    getAudioSendPacketLossAvg: () => Promise<number>;
    getAudioSendPacketLossMax: () => Promise<number>;
    getVideoStatisticsInfo: () => Promise<ZoomVideoSdkSessionVideoStatisticsInfoType>;
    getVideoRecvFps: () => Promise<number>;
    getVideoRecvFrameHeight: () => Promise<number>;
    getVideoRecvFrameWidth: () => Promise<number>;
    getVideoRecvJitter: () => Promise<number>;
    getVideoRecvLatency: () => Promise<number>;
    getVideoRecvPacketLossAvg: () => Promise<number>;
    getVideoRecvPacketLossMax: () => Promise<number>;
    getVideoSendFps: () => Promise<number>;
    getVideoSendFrameHeight: () => Promise<number>;
    getVideoSendFrameWidth: () => Promise<number>;
    getVideoSendJitter: () => Promise<number>;
    getVideoSendLatency: () => Promise<number>;
    getVideoSendPacketLossAvg: () => Promise<number>;
    getVideoSendPacketLossMax: () => Promise<number>;
    getShareStatisticsInfo: () => Promise<ZoomVideoSdkSessionShareStatisticsInfoType>;
    getShareRecvFps: () => Promise<number>;
    getShareRecvFrameHeight: () => Promise<number>;
    getShareRecvFrameWidth: () => Promise<number>;
    getShareRecvJitter: () => Promise<number>;
    getShareRecvLatency: () => Promise<number>;
    getShareRecvPacketLossAvg: () => Promise<number>;
    getShareRecvPacketLossMax: () => Promise<number>;
    getShareSendFps: () => Promise<number>;
    getShareSendFrameHeight: () => Promise<number>;
    getShareSendFrameWidth: () => Promise<number>;
    getShareSendJitter: () => Promise<number>;
    getShareSendLatency: () => Promise<number>;
    getShareSendPacketLossAvg: () => Promise<number>;
    getShareSendPacketLossMax: () => Promise<number>;
};
export declare class ZoomVideoSdkSession implements ZoomVideoSdkSessionType {
    getSessionName(): Promise<any>;
    getSessionPassword(): Promise<any>;
    getSessionHostName(): Promise<any>;
    getSessionID(): Promise<any>;
    getSessionHost(): Promise<ZoomVideoSdkUser>;
    getRemoteUsers(): Promise<any>;
    getMySelf(): Promise<ZoomVideoSdkUser>;
    getSessionNumber(): Promise<any>;
    getSessionPhonePasscode(): Promise<any>;
    getAudioStatisticsInfo(): Promise<any>;
    getAudioRecvFrequency(): Promise<any>;
    getAudioRecvJitter(): Promise<any>;
    getAudioRecvLatency(): Promise<any>;
    getAudioRecvPacketLossAvg(): Promise<any>;
    getAudioRecvPacketLossMax(): Promise<any>;
    getAudioSendFrequency(): Promise<any>;
    getAudioSendJitter(): Promise<any>;
    getAudioSendLatency(): Promise<any>;
    getAudioSendPacketLossAvg(): Promise<any>;
    getAudioSendPacketLossMax(): Promise<any>;
    getVideoStatisticsInfo(): Promise<any>;
    getVideoRecvFps(): Promise<any>;
    getVideoRecvFrameHeight(): Promise<any>;
    getVideoRecvFrameWidth(): Promise<any>;
    getVideoRecvJitter(): Promise<any>;
    getVideoRecvLatency(): Promise<any>;
    getVideoRecvPacketLossAvg(): Promise<any>;
    getVideoRecvPacketLossMax(): Promise<any>;
    getVideoSendFps(): Promise<any>;
    getVideoSendFrameHeight(): Promise<any>;
    getVideoSendFrameWidth(): Promise<any>;
    getVideoSendJitter(): Promise<any>;
    getVideoSendLatency(): Promise<any>;
    getVideoSendPacketLossAvg(): Promise<any>;
    getVideoSendPacketLossMax(): Promise<any>;
    getShareStatisticsInfo(): Promise<any>;
    getShareRecvFps(): Promise<any>;
    getShareRecvFrameHeight(): Promise<any>;
    getShareRecvFrameWidth(): Promise<any>;
    getShareRecvJitter(): Promise<any>;
    getShareRecvLatency(): Promise<any>;
    getShareRecvPacketLossAvg(): Promise<any>;
    getShareRecvPacketLossMax(): Promise<any>;
    getShareSendFps(): Promise<any>;
    getShareSendFrameHeight(): Promise<any>;
    getShareSendFrameWidth(): Promise<any>;
    getShareSendJitter(): Promise<any>;
    getShareSendLatency(): Promise<any>;
    getShareSendPacketLossAvg(): Promise<any>;
    getShareSendPacketLossMax(): Promise<any>;
}
